import useSession from '@/contexts/AuthContext'
import { api } from '@/services/api'
import { IUser } from '@/types'
import axios from 'axios'
import { GetServerSideProps, GetStaticProps } from 'next'
import Head from 'next/head'
import { parseCookies } from "nookies" 

interface Props {
  posts: any[]
}

export default function Home({ posts }: Props) {

  const { user } = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello, {user?.name}</h1>
        {
          posts.map((post, index) =>{
            return <p key={index}>{post.title}</p>
          })
        }
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await axios.get("https://tabnews.com.br/api/v1/contents")
  const posts = response.data

  
  return {
    props: {
      posts
    },
  }
}